# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - .pre
  - build
  - test

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

services:
  - docker:28-dind

default:
  tags:
    - docker

prepare_environment:
  stage: .pre
  image: alpine:3.21.3
  script:
    - |
      apk add --update curl
      curl https://get.psono.com/psono/psono-ci/x86_64-linux/psonoci --output psonoci && chmod +x psonoci
      cp "${PSONO_CONFIG}" .psono-config.conf
      source .psono-config.conf
      rm -f .psono-config.conf
    - CI_REGISTRY="$(./psonoci env-vars get-or-create 5497576f-d518-47cc-89ba-b9329f83897a CI_REGISTRY)"
    - CI_REGISTRY_IMAGE_PREFIX="$(./psonoci env-vars get-or-create 5497576f-d518-47cc-89ba-b9329f83897a CI_REGISTRY_IMAGE_PREFIX)"
    - CI_REGISTRY_PASSWORD="$(./psonoci env-vars get-or-create 5497576f-d518-47cc-89ba-b9329f83897a CI_REGISTRY_PASSWORD)"
    - CI_REGISTRY_USER="$(./psonoci env-vars get-or-create 5497576f-d518-47cc-89ba-b9329f83897a CI_REGISTRY_USER)"
    - GIT_STRATEGY="fetch"
    - CS_IMAGE="$CI_REGISTRY_IMAGE_PREFIX/pre-commit:$CI_COMMIT_REF_SLUG"
    - DOCKER_IMAGE_NAME="$CI_REGISTRY_IMAGE_PREFIX/pre-commit:$CI_COMMIT_REF_SLUG"
    - CI_REGISTRY_IMAGE="$CI_REGISTRY_IMAGE_PREFIX/pre-commit"
    - echo "CI_REGISTRY=$CI_REGISTRY" >> variables.env
    - echo "CI_REGISTRY_IMAGE_PREFIX=$CIREGISTRY_IMAGE_PREFIX" >> variables.env
    - echo "CI_REGISTRY_PASSWORD=$CI_REGISTRY_PASSWORD" >> variables.env
    - echo "CI_REGISTRY_USER=$CI_REGISTRY_USER" >> variables.env
    - echo "GIT_STRATEGY=fetch" >> variables.env
    - echo "CS_IMAGE=$CS_IMAGE" >> variables.env
    - echo "DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME" >> variables.env
    - echo "CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env

sast:
  stage: test

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/SAST-IaC.latest.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - component: gitlab.com/docker-scout/ci/cves@main
    inputs:
      stage: test
      options: --only-severity=critical,high,medium --epss

docker-scout-cves:
  dependencies:
    - prepare_environment

container_scanning:
  dependencies:
    - prepare_environment

docker-build:
  image: docker:latest
  stage: build
  dependencies:
    - prepare_environment
  script:
    - echo -n "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build --no-cache -t "$DOCKER_IMAGE_NAME" .
    - |
      if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        docker push "$DOCKER_IMAGE_NAME"
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_COMMIT_BRANCH"
  after_script:
    - docker logout $CI_REGISTRY
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
