prepare_scanning:
  stage: test
  image: docker
  cache:
    - key: cache-$CI_COMMIT_REF_SLUG
      paths:
        - psonoci
        - .psonoci.toml
      policy: push
  script:
    - apk add --update curl
    - curl https://get.psono.com/psono/psono-ci/x86_64-linux/psonoci --output psonoci && chmod +x psonoci
    - cp "${PSONO_CONFIG}" .psonoci.toml

container_scanning:
  variables:
    - GIT_STRATEGY: fetch
  cache:
    - key: cache-$CI_COMMIT_REF_SLUG
      paths:
        - psonoci
        - .psonoci.toml
      policy: pull
  needs:
    - job: prepare_scanning
      optional: false
      artifacts: true
  before_script:
    - export CS_PSONO_REGISTRY=$(./psonoci -c ./.psonoci.toml env-vars get-or-create ${PSONO_GITLAB_CONTAINER_REGISTRY} CI_REGISTRY)
    - export CS_PSONO_REGISTRY_PASSWORD=$(./psonoci -c ./.psonoci.toml env-vars get-or-create ${PSONO_GITLAB_CONTAINER_REGISTRY} CI_REGISTRY_PASSWORD)
    - export CS_PSONO_REGISTRY_USER=$(./psonoci -c ./.psonoci.toml env-vars get-or-create ${PSONO_GITLAB_CONTAINER_REGISTRY} CI_REGISTRY_USER)
    - export CS_IMAGE="${CS_PSONO_REGISTRY}/jfheinrich-dev/pre-commit:build"
    - export CS_REGISTRY_USER="${CS_PSONO_REGISTRY_USER}"
    - export CS_REGISTRY_PASSWORD="${CS_PSONO_REGISTRY_PASSWORD}"

include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml
