production:
  stage: production
  image: docker
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/
      when: manual
  services:
    - docker:dind
  before_script:
    - apk add --update make
    - echo "${DOCKER_HUB_PASSWORD}" | docker login -u $DOCKER_HUB_USER -password-stdin
  script:
    - make ci-build-and-push
  after_script:
    - docker logout
  environment:
    name: production
    url: https://hub.docker.com/r/jfheinrich/pre-commit
