staging:
  stage: staging
  image: docker
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == 'develop'
      when: manual
  services:
    - docker:dind
  before_script:
    - apk add --update make
    - echo "${PAT}" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER -password-stdin
  script:
    - make -e image_tag=$CI_COMNMIT_BRANCH-$CI_COMMIT_SHA ci-build-staging
  after_script:
    - docker logout $CI_REGISTRY
  environment:
    name: staging
