pre-commit:
  stage: test
  image:
    name: jfheinrich/pre-commit:latest
    entrypoint: [""]
  variables:
    MERGE_REQUEST_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}/changes"
  before_script:
    - apk add --update jq curl
  script:
    - |
      curl --request GET --header "PRIVATE-TOKEN: ${PAT}" --url ${MERGE_REQUEST_URL} > mr-infos.json
      export files="$(jq -r '.changes[] | if .deleted_file == false then .new_path else null end' mr-infos.json)"
    - '[[ -z "$files" ]] || pre-commit run --color always --config .pre-commit-config.yaml --files $(echo $files)'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
