prepare-production:
  extends:
    - .prepare_psono
  stage: production
  script:
    - 'echo "CI_PSONO_REGISTRY=$(./psonoci -c ./.psonoci.toml env-vars get-or-create ${PSONO_DOCKERHUB_REGISTRY_ID} CI_REGISTRY)" >> variables.env'
    - 'echo "CI_PSONO_REGISTRY_PASSWORD=$(./psonoci -c ./.psonoci.toml env-vars get-or-create ${PSONO_DOCKERHUB_REGISTRY_ID} CI_REGISTRY_PASSWORD)" >> variables.env'
    - 'echo "CI_PSONO_REGISTRY_USER=$(./psonoci -c ./.psonoci.toml env-vars get-or-create ${PSONO_DOCKERHUB_REGISTRY_ID} CI_REGISTRY_USER)" >> variables.env'
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/
  artifacts:
    reports:
      dotenv: variables.env

production:
  stage: production
  image: docker
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/
      when: manual
  needs:
    - job: prepare-production
      optional: false
      artifacts: true
  services:
    - docker:dind
  before_script:
    - apk add --update make docker-cli-buildx
    - echo "${CI_PSONO_REGISTRY_PASSWORD}" | docker login -u $CI_PSONO_REGISTRY_USER --password-stdin
  script:
    - make -e image_tag=$CI_COMMIT_TAG ci-build-and-push
  after_script:
    - docker logout
  environment:
    name: production
    url: https://hub.docker.com/r/jfheinrich/pre-commit
