create-release-tag:
  stage: release
  image: registry.gitlab.com/gitlab-ci-utils/curl-jq:latest
  variables:
    CREATE_TAG_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/tags?tag_name=${GitVersion_MajorMinorPatch}&ref=${CI_COMMIT_BRANCH}&message=v${GitVersion_MajorMinorPatch}"
    tag: "${GitVersion_MajorMinorPatch}"
  script:
    - 'curl --request POST --header "PRIVATE-TOKEN: ${PAT}" --url "${CREATE_TAG_URL}"'
    - 'curl --fail --request POST --form token=$TRIGGER_TOKEN --form ref=${tag} "${CI_API_V4_URL}/projects/${CI_PROJECT_TRIGGER}/trigger/pipeline"'
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == 'main'
