prepare_release:
  image: node:lts-alpine
  needs:
    - job: create-changelog
      optional: false
      artifacts: true
    - job: update-buid-version
      optional: false
  variables:
    release:
      value: '{"defaults":{"name":"$$CHANGELOG","description":"$$CHANGELOG"}}'
      expand: false
  before_script:
    - npm install -g gitlab-releaser
    - |
      if [ ! -f .gitlab/gitlab-release.json ]; then
        mkdir -p .gitlab && echo $RELEASE > .gitlab/gitlab-releaser.json
      fi
  script:
    - gitlab-releaser
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/
  artifacts:
    paths:
      - ".gitlab/release.json"

create_release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: prepare_release
      optional: false
      artifacts: true
  script:
    - echo "running release_job for $CI_COMMIT_TAG"
    - release-cli create-from-file -file .gitlab/release.json
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/
