name: Deploy

permissions:
  contents: read

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  changelog:
    uses: ./.github/workflows/changelog.yml
    secrets: inherit

  publish-github:
    uses: ./.github/workflows/publish.yml
    with:
      image_name: 'pre-commit'
    secrets: inherit
