name: Deploy

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  changelog:
    uses: ./.github/workflows/changelog.yml
    secrets: inherit

  publish-github:
    uses: ./.github/workflows/publish.yml
    secrets: inherit
