name: Deploy

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  changelog:
    permissions:
      contents: write
    uses: ./.github/workflows/changelog.yml
    secrets: inherit

  publish-github:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/publish.yml
    with:
      image_name: 'pre-commit'
    secrets: inherit
