name: Deploy

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

  changelog:
    uses: ./.github/workflows/changelog.yml

  publish-github:
    uses: ./.github/workflows/publish.yml
