name: Publish

on:
  workflow_call:

jobs:
  secrets-github:
    uses: jfheinrich-eu/reusable-workflows/.github/workflows/secrets-github-registry.yml@master
  secrets-dockerhub:
    uses: jfheinrich-eu/reusable-workflows/.github/workflows/secrets-dockerhub-registry.yml@master
    with:
      image_name: 'pre-commit'

  publish:
    needs:
      - secrets-github
      - secrets-dockerhub
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - id: setup-secrets
        name: Setup secrets
        env:
          GITHUB_CI_REGISTRY: ${{ needs.secrets-github.outputs.CI_REGISTRY }}
          GITHUB_IMAGE: ${{ needs.secrets-github.outputs.CS_IMAGE_PUBLISH }}
          DOCKERHUB_CI_REGISTRY: ${{ needs.secrets-dockerhub.outputs.CI_REGISTRY }}
          DOCKERHUB_IMAGE: ${{ needs.secrets-dockerhub.outputs.CS_IMAGE_PUBLISH }}
        run: |
          echo "github_cs_image=${GITHUB_IMAGE}" >> "$GITHUB_OUTPUT"
          echo "dockerhub_cs_image=${DOCKERHUB_IMAGE}" >> "$GITHUB_OUTPUT"
          echo "build_date=$(date --iso-8601=seconds)" >> "$GITHUB_OUTPUT"
          echo "build_version=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"

      - id: github-docker-login
        name: GitHub Docker Login
        uses: docker/login-action@v3.4.0
        with:
            registry: ${{ needs.secrets-github.outputs.CI_REGISTRY }}
            username: ${{ needs.secrets-github.outputs.CI_REGISTRY_USER }}
            password: ${{ needs.secrets-github.outputs.CI_REGISTRY_PASSWORD }}
            ecr: auto
            logout: true

      - id: dockerhub-docker-login
        name: DockerHub Docker Login
        uses: docker/login-action@v3.4.0
        with:
            username: ${{ needs.secrets-dockerhub.outputs.CI_REGISTRY_USER }}
            password: ${{ needs.secrets-dockerhub.outputs.CI_REGISTRY_PASSWORD }}
            ecr: auto
            logout: true

      - name: Set up Docker buildx
        id: setup-docker-buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Build and push
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./src
          # depends on the base image python: 3-alpine3.21
          platforms: linux/386, linux/amd64, linux/arm/v6
          push: true
          tags: |
            ${{ needs.secrets-github.outputs.CS_IMAGE_PUBLISH }}
            ${{ needs.secrets-dockerhub.outputs.CS_IMAGE_PUBLISH }}
          build-args: (BUILD_DATE=${{ needs.secrets-github.outputs.BUILD_DATE }}, VERSION=${{ needs.secrets-github.outputs.PUBLISH_VERSION }})

